// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: batch_insert.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertErroredFile = `-- name: InsertErroredFile :exec
INSERT INTO errored_files (
    filename,
    error
) VALUES (
    $1,
    $2
)
`

type InsertErroredFileParams struct {
	Filename string
	Error    string
}

func (q *Queries) InsertErroredFile(ctx context.Context, arg InsertErroredFileParams) error {
	_, err := q.db.Exec(ctx, insertErroredFile, arg.Filename, arg.Error)
	return err
}

const insertRecord = `-- name: InsertRecord :exec
INSERT INTO records (
    n,
    mqtt,
    invid,
    unit_guid,
    msg_id,
    text,
    context,
    class,
    level,
    area,
    addr,
    block,
    type,
    bit,
    invert_bit
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15
)
`

type InsertRecordParams struct {
	N         int32
	Mqtt      pgtype.Text
	Invid     string
	UnitGuid  string
	MsgID     string
	Text      string
	Context   pgtype.Text
	Class     string
	Level     int32
	Area      string
	Addr      string
	Block     pgtype.Text
	Type      pgtype.Text
	Bit       pgtype.Text
	InvertBit pgtype.Text
}

func (q *Queries) InsertRecord(ctx context.Context, arg InsertRecordParams) error {
	_, err := q.db.Exec(ctx, insertRecord,
		arg.N,
		arg.Mqtt,
		arg.Invid,
		arg.UnitGuid,
		arg.MsgID,
		arg.Text,
		arg.Context,
		arg.Class,
		arg.Level,
		arg.Area,
		arg.Addr,
		arg.Block,
		arg.Type,
		arg.Bit,
		arg.InvertBit,
	)
	return err
}
